apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  name: ingress-nginx
  namespace: postgres
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: acid-minimal-cluster
          servicePort: 5432
        path: /postgres
        pathType: Prefix
status:
  loadBalancer: {}
